//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTUDW_CTLH_C1.Administration.Admin {
    
    
    public partial class TinTuc {
        
        /// <summary>
        /// wucQuanLyTinTuc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PTUDW_CTLH_C1.WUC.TinTuc.wucQuanLyTinTuc wucQuanLyTinTuc;
    }
}
